### ISSUE TITLE
Find entries that a member is associated with

### ISSUE THREAD

**Issue by nathanpitman** [elivz/vz_members#5]
How would I do a reverse lookup using VZ Members within a template, i.e. instead of returning all members associated with an entry, specify a member_id and return all entries associated with her/him?

:)

**Comment by elivz** [comment]
Hmm, not really possible at the moment. You could almost use channel:entries' "search" parameter, except that it would match subsets, so if you searched for member ID "5", it would also return ID "15". It could be modified fairly easily so the stored value includes vertical bars at the beginning and end of the value in the database (`|1|15|30|`), and then you could use `search:members_field="|5|"` to get just the entries with member 5 selected. I'll put that on my list to add in the next release, but in the mean time you can change line 337 to:

```
return '|'.$field_data.'|';
```

You will have to resave existing entries before they will be searchable this way.

**Comment by nathanpitman** [comment]
Thanks @elivz :)

**Comment by elivz** [comment]
I actually neglected to account for the empty values that will include on output, so I went ahead and pushed out version 1.0.9, which includes a more complete solution. Let me know if that works for your use-case.
